apiVersion: v1
kind: ConfigMap
metadata:
  name: upload-widget-server-cm
  namespace: upload-widget
data:
  CLOUDFLARE_BUCKET: "#"
  CLOUDFLARE_PUBLIC_URL: "http://localhost"
  SECRET_API_VERSION: "v1"
  SECRET_API_ENDPOINT: "http://192.168.1.121:8200"
  VAULT_ADDR: "http://vault:8200"
