apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: upload-widget-server-hpa-legacy
  namespace: upload-widget
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upload-widget-server-deployment
  minReplicas: 3
  maxReplicas: 8
  targetCPUUtilizationPercentage: 75
