apiVersion: v1
kind: Secret
metadata:
  name: upload-widget-server-secret
  namespace: upload-widget
type: Opaque
data:
  CLOUDFLARE_ACCESS_KEY_ID: ""
  CLOUDFLARE_SECRET_ACCESS_KEY: ""
  CLOUDFLARE_ACCOUNT_ID: ""
  NEW_RELIC_APP_NAME: ""
  NEW_RELIC_LICENSE_KEY: ""
  SECRET_API_TOKEN: ""
  VAULT_TOKEN: ""
