apiVersion: v1
kind: Service
metadata:
  name: upload-widget-server-svc
  namespace: upload-widget
spec:
  type: ClusterIP
  selector:
    app: upload-widget-server
  ports:
    - port: 80
      targetPort: 3333
